DROP TABLE IF EXISTS `payments`;
CREATE TABLE `payments` (
  `payment_number` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_number` INT(10) UNSIGNED NOT NULL,
  `payment_method` ENUM('IDEAL', 'VISA', 'MASTERCARD', 'PAYPAL') NOT NULL, 
  `total_amount` DECIMAL(12,2) UNSIGNED NOT NULL,
  `status` ENUM('AUTHORIZED', 'CANCELED', 'PENDING', 'EXPIRED', 'FAILED', 'REFUND PENDING', 'REFUNDED') NOT NULL,
  `paid_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT pk_payments PRIMARY KEY (`payment_number`),
  CONSTRAINT fk_payment_order FOREIGN KEY (`order_number`)
  REFERENCES orders(`order_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
